### ISSUE TITLE
请问可以求一份课程的资源吗？

### ISSUE THREAD

**Issue by MaXiaoYang6** [shinezzz/AcWingBasicAlgorithmCourse#1]
请问可以求一份课程的资源吗？ Email:396434855@qq.com

**Comment by shinezzz** [comment]
视频是在线看。这些题目就是我有的算法基础课的资源。

**Comment by shinezzz** [comment]
> 
> 
> 请问可以求一份课程的资源吗？ Email:[396434855@qq.com](mailto:396434855@qq.com)

视频是在线看。这些题目就是我有的算法基础课的资源。
